title: Site

tabs:

  content:
    label: Content
    icon: home

    columns:

      - width: 1/2
        sections:

          channels:
            extends: sections/pages
            headline: Channels
            template: channel
            info: "{{ page.info }}"

          pages:
            extends: sections/pages
            headline: Other pages
            templates:
              - info
              - default
            create:
              - default

      - width: 1/2
        fields:

          featured: fields/featured

  meta:
    extends: tabs/meta

  settings:
    icon: cog
    columns:

      - width: 1/2
        fields:

          layout: fields/layoutSelect

      - width: 1/2
        fields:

          dateFormat: fields/dateFormatSelect
